PACKAGE_NAME="mt7902"
PACKAGE_VERSION=1.0.0

MAKE="make -C mt76 KVER=$kernelver"
CLEAN="make -C mt76 KVER=$kernelver clean"

BUILT_MODULE_NAME[0]="mt76"
BUILT_MODULE_NAME[1]="mt76-connac-lib"
BUILT_MODULE_NAME[2]="mt792x-lib"
BUILT_MODULE_NAME[3]="mt7921-common"
BUILT_MODULE_NAME[4]="mt7921e"

BUILT_MODULE_LOCATION[0]="mt76"
BUILT_MODULE_LOCATION[1]="mt76"
BUILT_MODULE_LOCATION[2]="mt76"
BUILT_MODULE_LOCATION[3]="mt76"
BUILT_MODULE_LOCATION[4]="mt76"

DEST_MODULE_LOCATION[0]="/updates/dkms"
DEST_MODULE_LOCATION[1]="/updates/dkms"
DEST_MODULE_LOCATION[2]="/updates/dkms"
DEST_MODULE_LOCATION[3]="/updates/dkms"
DEST_MODULE_LOCATION[4]="/updates/dkms"

AUTOINSTALL="yes"
REMAKE_INITRD=yes
